# KYC Verification routes
ps_pskyc_verification_index:
  path: /pskyc/verification
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\Pskyc\Controller\Admin\VerificationController::indexAction'

ps_pskyc_verification_search:
  path: /pskyc/verification/search
  methods: [POST]
  defaults:
    _controller: 'PrestaShop\Module\Pskyc\Controller\Admin\VerificationController::searchAction'

ps_pskyc_verification_view:
  path: /pskyc/verification/{verificationId}/view
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\Pskyc\Controller\Admin\VerificationController::viewAction'
  requirements:
    verificationId: \d+

ps_pskyc_verification_update_note:
  path: /pskyc/verification/{verificationId}/update-note
  methods: [POST]
  defaults:
    _controller: 'PrestaShop\Module\Pskyc\Controller\Admin\VerificationController::updateNoteAction'
  requirements:
    verificationId: \d+

ps_pskyc_document_download:
  path: /pskyc/document/{documentId}/{preview}
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\Pskyc\Controller\Admin\DocumentController::downloadAction'
    preview: 0
  requirements:
    documentId: '\d+'
    preview: '\d+'

ps_pskyc_document_update_status:
  path: /pskyc/verification/{verificationId}/documents/update-status
  methods: [POST]
  defaults:
    _controller: 'PrestaShop\Module\Pskyc\Controller\Admin\DocumentController::updateStatusAction'
  requirements:
    verificationId: \d+