name: CI Tests

on: [push, pull_request]

jobs:
  # PHP syntax checking using official PrestaShop actions
  php-linter:
    name: PHP Syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@master

      - name: PHP syntax checker 8.2
        uses: prestashop/github-action-php-lint/8.2@master

      - name: PHP syntax checker 8.3
        uses: prestashop/github-action-php-lint/8.3@master

  # Check the PHP code follows coding standards
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: php-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: composer install

      - name: Run PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no

  # Run PHPStan against the module and PrestaShop releases
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presta-versions: ['8.0', '8.1', 'latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache vendor folder
        uses: actions/cache@v4
        with:
          path: vendor
          key: php-${{ hashFiles('composer.lock') }}

      - name: Cache composer folder
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: php-composer-cache

      - name: Install dependencies
        run: composer install

      - name: Execute PHPStan on PrestaShop (Tag ${{ matrix.presta-versions }})
        run: ./tests/phpstan.sh ${{ matrix.presta-versions }}

  # PHPUnit tests
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache vendor folder
        uses: actions/cache@v4
        with:
          path: vendor
          key: php-${{ hashFiles('composer.lock') }}

      - name: Cache composer folder
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: php-composer-cache

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: |
          mkdir -p coverage
          vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover coverage/clover.xml